-- Откат scripts/datafix_2026-09-26.sql
begin;
update baths set name = 'Минск, the  Баня', type = 'public', country = 'Беларусь', region = 'Минск', precision = 'city', created_by = NULL where id = 30;
update baths set name = 'Висмар, Krusespeicher', type = NULL, country = 'Германия', region = 'Mecklenburg-Vorpommern', precision = 'city', created_by = NULL where id = 55;
update baths set name = 'Дом отдыха "Три чайки", Zierow', type = NULL, country = 'Германия', region = 'Mecklenburg-Vorpommern', precision = 'region', created_by = NULL where id = 56;
update baths set name = 'De Poeler Drift 5А,', type = NULL, country = 'Германия', region = 'Mecklenburg-Vorpommern', precision = 'exact', created_by = NULL where id = 57;
update baths set name = 'Гамбург, Bäderland Alsterschwimmhalle', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'city', created_by = NULL where id = 58;
update baths set name = 'Гамбург, Baderland Festland', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'city', created_by = NULL where id = 59;
update baths set name = 'Гамбург, Bartholomäus Therme', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'city', created_by = NULL where id = 60;
update baths set name = 'Гамбург, Holthusenbad', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'city', created_by = NULL where id = 61;
update baths set name = 'Campusbad Фленсбург', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'exact', created_by = NULL where id = 62;
update baths set name = 'Kiekut Saunabus', type = NULL, country = 'Германия', region = 'Schleswig-Holstein', precision = 'region', created_by = NULL where id = 63;
update baths set name = 'Германия,  Tropical island', type = 'public', country = 'Германия', region = NULL, precision = 'city', created_by = NULL where id = 64;
update baths set name = 'Германия, аквапарк Мирамар', type = 'public', country = 'Германия', region = NULL, precision = 'city', created_by = NULL where id = 65;
update baths set name = 'Германия, Кёльн, Claudius therms', type = 'public', country = 'Германия', region = NULL, precision = 'city', created_by = NULL where id = 66;
update baths set name = 'Германия, Мюнхен, Freizeitbad Pullach', type = NULL, country = 'Германия', region = NULL, precision = 'city', created_by = NULL where id = 67;
update baths set name = 'Германия, Buhl, Schwitztube', type = NULL, country = 'Германия', region = NULL, precision = 'city', created_by = NULL where id = 68;
update baths set name = 'Рига, баня 1', type = 'public', country = 'Латвия', region = 'Рига', precision = 'exact', created_by = NULL where id = 107;
update baths set name = 'Рига, Radisson Elizabete хуитнес', type = 'public', country = 'Латвия', region = 'Рига', precision = 'city', created_by = NULL where id = 120;
update baths set name = 'Латвия, Валмиера, Peldbaseinu', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 122;
update baths set name = 'Латвия, Валмиерская', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 123;
update baths set name = 'Латвия, Вентспилс городская', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 124;
update baths set name = 'Латвия, Клайпедские', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 125;
update baths set name = 'Латвия, Кулдига Городская', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 126;
update baths set name = 'Латвия, Лиепая, Lacis', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 127;
update baths set name = 'Латвия, у Рейниса', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 128;
update baths set name = 'Латвия, Salaspils городская', type = 'spa', country = 'Латвия', region = NULL, precision = 'city', created_by = NULL where id = 129;
update baths set name = 'Вильнюс, Виши аквапарк', type = 'public', country = 'Литва', region = 'Вильнюс', precision = 'city', created_by = NULL where id = 131;
update baths set name = 'Литва, Sillamäe городская', type = 'spa', country = 'Литва', region = NULL, precision = 'city', created_by = NULL where id = 133;
update baths set name = 'Мексика, Мехико,  Amsterdam 43', type = NULL, country = 'Мексика', region = NULL, precision = 'city', created_by = NULL where id = 136;
update baths set name = 'Амстер,  Hima spa', type = 'private', country = 'Нидерланды', region = 'Амстердам', precision = 'region', created_by = NULL where id = 143;
update baths set name = 'Амстер, хуитнес', type = 'private', country = 'Нидерланды', region = 'Амстердам', precision = 'region', created_by = NULL where id = 144;
update baths set name = 'Барнаул, баня 24', type = 'private', country = 'Россия', region = 'Алтайский край', precision = 'exact', created_by = NULL where id = 174;
update baths set name = 'Барнаул, баня 36', type = 'private', country = 'Россия', region = 'Алтайский край', precision = 'exact', created_by = NULL where id = 175;
update baths set name = 'Благовещенск, баня 3', type = 'spa', country = 'Россия', region = 'Амурская обл', precision = 'exact', created_by = NULL where id = 180;
update baths set name = 'Благовещенск, баня 6', type = 'spa', country = 'Россия', region = 'Амурская обл', precision = 'exact', created_by = NULL where id = 181;
update baths set name = 'Улан-Удэ, баня 1', type = NULL, country = 'Россия', region = 'Бурятия', precision = 'exact', created_by = NULL where id = 192;
update baths set name = 'Улан-Удэ, баня 5', type = NULL, country = 'Россия', region = 'Бурятия', precision = 'exact', created_by = NULL where id = 193;
update baths set name = 'Улан-Удэ, баня 8', type = NULL, country = 'Россия', region = 'Бурятия', precision = 'exact', created_by = NULL where id = 194;
update baths set name = 'Воронеж, баня 10', type = NULL, country = 'Россия', region = 'Воронежская обл', precision = 'exact', created_by = NULL where id = 212;
update baths set name = 'Воронеж, баня 8', type = NULL, country = 'Россия', region = 'Воронежская обл', precision = 'exact', created_by = NULL where id = 213;
update baths set name = 'Иркутск, баня 10', type = 'public', country = 'Россия', region = 'Иркутская обл', precision = 'exact', created_by = NULL where id = 225;
update baths set name = 'Иркутск, баня 2', type = 'public', country = 'Россия', region = 'Иркутская обл', precision = 'exact', created_by = NULL where id = 226;
update baths set name = 'Иркутск, баня 8', type = 'public', country = 'Россия', region = 'Иркутская обл', precision = 'exact', created_by = NULL where id = 227;
update baths set name = 'Кёниг, Лëд', type = NULL, country = 'Россия', region = 'Калининградская обл', precision = 'city', created_by = NULL where id = 249;
update baths set name = 'Частная, Тарусская Скульпторская', type = 'private', country = 'Россия', region = 'Калужская обл', precision = 'region', created_by = NULL where id = 260;
update baths set name = 'Петрозаводск, баня 1', type = 'public', country = 'Россия', region = 'Карелия', precision = 'exact', created_by = NULL where id = 273;
update baths set name = 'Петрозаводск, баня 5', type = 'public', country = 'Россия', region = 'Карелия', precision = 'exact', created_by = NULL where id = 274;
update baths set name = 'Петрозаводск, баня 8', type = 'public', country = 'Россия', region = 'Карелия', precision = 'exact', created_by = NULL where id = 275;
update baths set name = 'Сыктывкар, баня 10', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 300;
update baths set name = 'Сыктывкар, баня 11', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 301;
update baths set name = 'Сыктывкар, баня 3', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 302;
update baths set name = 'Сыктывкар, баня 4', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 303;
update baths set name = 'Сыктывкар, баня 5', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 304;
update baths set name = 'Сыктывкар, баня 6', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 305;
update baths set name = 'Сыктывкар, баня 7', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 306;
update baths set name = 'Сыктывкар, баня 8', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 307;
update baths set name = 'Сыктывкар, баня 9', type = 'public', country = 'Россия', region = 'Коми', precision = 'exact', created_by = NULL where id = 308;
update baths set name = 'Хуитнес Атлант бассейн', type = 'public', country = 'Россия', region = 'Москва', precision = 'exact', created_by = NULL where id = 465;
update baths set name = 'Хуитнес Банифаций', type = 'public', country = 'Россия', region = 'Москва', precision = 'exact', created_by = NULL where id = 466;
update baths set name = 'Хуитнес DDX  Мозаика', type = 'spa', country = 'Россия', region = 'Москва', precision = 'region', created_by = NULL where id = 476;
update baths set name = 'Хуитнес the base  крылатское', type = 'spa', country = 'Россия', region = 'Москва', precision = 'region', created_by = NULL where id = 495;
update baths set name = 'Хуитнес, Spiritness  Гагаринский', type = 'spa', country = 'Россия', region = 'Москва', precision = 'region', created_by = NULL where id = 509;
update baths set name = 'Хуитнес, Spiritness  Сити', type = 'spa', country = 'Россия', region = 'Москва', precision = 'region', created_by = NULL where id = 510;
update baths set name = 'Хуитнес, Spiritness  Ясенево', type = 'spa', country = 'Россия', region = 'Москва', precision = 'region', created_by = NULL where id = 511;
update baths set name = 'Частная, Деревенская у Тимура', type = 'private', country = 'Россия', region = 'Московская обл.', precision = 'region', created_by = NULL where id = 539;
update baths set name = 'Частная, Хомутово Тещина  банька', type = 'private', country = 'Россия', region = 'Московская обл', precision = 'region', created_by = NULL where id = 638;
update baths set name = 'Малевича бани, гранд вип', type = NULL, country = 'Россия', region = 'Московская обл.', precision = 'region', created_by = NULL where id = 644;
update baths set name = 'Малевича бани, мужской', type = NULL, country = 'Россия', region = 'Московская обл.', precision = 'region', created_by = NULL where id = 645;
update baths set name = 'Серпухов, пос. Пограничный, баня 1', type = NULL, country = 'Россия', region = 'Московская обл.', precision = 'city', created_by = NULL where id = 646;
update baths set name = 'Частная, Новосельцевская', type = 'private', country = 'Россия', region = 'Московская обл.', precision = 'region', created_by = NULL where id = 647;
update baths set name = 'Частная, Папертники', type = 'spa', country = 'Россия', region = 'Московская обл.', precision = 'region', created_by = NULL where id = 648;
update baths set name = 'Мурманск, баня 2', type = 'public', country = 'Россия', region = 'Мурманская обл', precision = 'exact', created_by = NULL where id = 649;
update baths set name = 'Мурманск, баня 3', type = 'public', country = 'Россия', region = 'Мурманская обл', precision = 'exact', created_by = NULL where id = 650;
update baths set name = 'Мурманск, баня 4', type = 'public', country = 'Россия', region = 'Мурманская обл', precision = 'exact', created_by = NULL where id = 651;
update baths set name = 'Бердск, частная у Оксаны и Вовчика', type = NULL, country = 'Россия', region = 'Новосибирская обл', precision = 'city', created_by = NULL where id = 668;
update baths set name = 'Солотча, баня на Новой ул.', type = NULL, country = 'Россия', region = 'Рязанская обл.', precision = 'city', created_by = NULL where id = 697;
update baths set name = 'Саратов, баня 11', type = NULL, country = 'Россия', region = 'Саратовская обл', precision = 'exact', created_by = NULL where id = 739;
update baths set name = 'Саратов, баня 2', type = NULL, country = 'Россия', region = 'Саратовская обл', precision = 'exact', created_by = NULL where id = 740;
update baths set name = 'Саратов, баня 4', type = NULL, country = 'Россия', region = 'Саратовская обл', precision = 'exact', created_by = NULL where id = 741;
update baths set name = 'Саратов, баня 7', type = NULL, country = 'Россия', region = 'Саратовская обл', precision = 'exact', created_by = NULL where id = 742;
update baths set name = 'Энгельс, частная Данюса', type = NULL, country = 'Россия', region = 'Саратовская обл', precision = 'city', created_by = NULL where id = 757;
update baths set name = 'Частная, Чувашская', type = 'private', country = 'Россия', region = 'Саратовская область', precision = 'region', created_by = NULL where id = 758;
update baths set name = 'Частная, Энгельс Рублевка', type = 'private', country = 'Россия', region = 'Саратовская область', precision = 'region', created_by = NULL where id = 759;
update baths set name = 'Частная, Энгельс ул. Победы', type = 'private', country = 'Россия', region = 'Саратовская область', precision = 'region', created_by = NULL where id = 760;
update baths set name = 'Частная, Энгельс, у Гагарина', type = 'private', country = 'Россия', region = 'Саратовская область', precision = 'region', created_by = NULL where id = 761;
update baths set name = 'Южно-Сахалинск, баня 37', type = NULL, country = 'Россия', region = 'Сахалинская обл', precision = 'exact', created_by = NULL where id = 764;
update baths set name = 'Южно-Сахалинск, баня 6', type = 'public', country = 'Россия', region = 'Сахалинская обл', precision = 'exact', created_by = NULL where id = 765;
update baths set name = 'Исток, "У завода"', type = 'public', country = 'Россия', region = 'Свердловская обл', precision = 'city', created_by = NULL where id = 768;
update baths set name = 'Северная Осетия, 1950', type = NULL, country = 'Россия', region = 'Северная Осетия', precision = 'exact', created_by = NULL where id = 784;
update baths set name = 'Юряхино деревня, частная', type = NULL, country = 'Россия', region = 'Тверская обл', precision = 'region', created_by = NULL where id = 819;
update baths set name = 'Томск, баня 12', type = NULL, country = 'Россия', region = 'Томская обл', precision = 'exact', created_by = NULL where id = 820;
update baths set name = 'Томск, баня 2', type = NULL, country = 'Россия', region = 'Томская обл', precision = 'exact', created_by = NULL where id = 822;
update baths set name = 'Томск, баня 3', type = NULL, country = 'Россия', region = 'Томская обл', precision = 'exact', created_by = NULL where id = 823;
update baths set name = 'Томск, баня 6', type = NULL, country = 'Россия', region = 'Томская обл', precision = 'exact', created_by = NULL where id = 824;
update baths set name = 'Частная, Комаревские', type = 'private', country = 'Россия', region = 'Тульская обл.', precision = 'region', created_by = NULL where id = 836;
update baths set name = 'Частная,Котенево', type = 'private', country = 'Россия', region = 'Тульская обл.', precision = 'region', created_by = NULL where id = 837;
update baths set name = 'Ижевск, частная СНТ Мебельщик', type = NULL, country = 'Россия', region = 'Удмуртия', precision = 'city', created_by = NULL where id = 845;
update baths set name = 'Чебоксары, Баня 1', type = 'public', country = 'Россия', region = 'Чувашия', precision = 'exact', created_by = NULL where id = 864;
update baths set name = 'Чебоксары, баня 2', type = NULL, country = 'Россия', region = 'Чувашия', precision = 'exact', created_by = NULL where id = 865;
update baths set name = 'Чебоксары, баня 3', type = 'public', country = 'Россия', region = 'Чувашия', precision = 'exact', created_by = NULL where id = 866;
update baths set name = 'Чебоксары, баня 7', type = NULL, country = 'Россия', region = 'Чувашия', precision = 'exact', created_by = NULL where id = 867;
update baths set name = 'Чебоксары, Баня 8', type = 'public', country = 'Россия', region = 'Чувашия', precision = 'exact', created_by = NULL where id = 868;
update baths set name = 'Рыбинск, баня 1', type = NULL, country = 'Россия', region = 'Ярославская обл', precision = 'exact', created_by = NULL where id = 876;
update baths set name = 'Рыбинск, баня 3', type = NULL, country = 'Россия', region = 'Ярославская обл', precision = 'exact', created_by = NULL where id = 877;
update baths set name = 'Эр-Рияд,  Soul spa', type = 'spa', country = 'Саудовская Аравия', region = NULL, precision = 'city', created_by = NULL where id = 928;
update baths set name = 'Бангкок,  Bangkok onsen', type = NULL, country = 'Таиланд', region = 'Бангкок', precision = 'city', created_by = NULL where id = 943;
update baths set name = 'Стамбул  Cesme', type = 'spa', country = 'Турция', region = 'Стамбул', precision = 'region', created_by = NULL where id = 958;
update baths set name = 'Стамбул,  Golden Horne', type = 'spa', country = 'Турция', region = 'Стамбул', precision = 'city', created_by = NULL where id = 959;
update baths set name = 'Хорватия, Дубровник, Excelsior hotel', type = 'public', country = 'Хорватия', region = NULL, precision = 'city', created_by = NULL where id = 989;
update baths set name = 'Хорватия, Дубровник, Sheraton Riviera hotel', type = 'public', country = 'Хорватия', region = NULL, precision = 'city', created_by = NULL where id = 990;
update baths set name = 'Чили, ОстровПасхи Nayara', type = 'public', country = 'Чили', region = NULL, precision = 'city', created_by = NULL where id = 993;
update baths set name = 'Швейцария, Льеж спа', type = 'spa', country = 'Швейцария', region = NULL, precision = 'city', created_by = NULL where id = 997;
update baths set name = 'Швейцария, Цюрих, Hallenbad', type = 'spa', country = 'Швейцария', region = NULL, precision = 'city', created_by = NULL where id = 998;
update baths set name = 'Швейцария, Chur Evertlagen', type = 'spa', country = 'Швейцария', region = NULL, precision = 'city', created_by = NULL where id = 999;
update baths set name = 'Швейцария, Engelberg', type = NULL, country = 'Швейцария', region = NULL, precision = 'city', created_by = NULL where id = 1000;
update baths set name = 'Швейцария, swisspeak', type = 'spa', country = 'Швейцария', region = NULL, precision = 'city', created_by = NULL where id = 1001;
update baths set name = 'Таллин, у Сани частная', type = 'public', country = 'Эстония', region = NULL, precision = 'city', created_by = NULL where id = 1004;
update baths set name = 'Потребкооперации Киров', type = 'public', country = 'Россия', region = 'Кировская обл', precision = 'exact', created_by = '4ff8b732-1d95-4e78-9223-8a57c3745875' where id = 1145;
commit;
