-- Журнал ошибок бота: что пришло и на чём упало. Видит только service role.
create table public.bot_log (
  id bigint generated by default as identity primary key,
  at timestamptz not null default now(),
  kind text not null,
  detail text
);
alter table public.bot_log enable row level security;
grant all on public.bot_log to service_role;
grant usage, select on sequence public.bot_log_id_seq to service_role;
