-- Действия бота по просьбе владельца — например, поменять реакцию на сообщении в чате (07.10: 🤔 на ссылке Шурика, а точку
-- поставили руками). Токен бота есть только у функции, поэтому сюда пишут (service_role, из базы), а бот выполняет:
-- триггер зовёт tg-bot?actions=1. Участникам и сайту таблица недоступна.
create table public.bot_actions (
  id bigint generated by default as identity primary key,
  kind text not null check (kind in ('react')),
  chat_id bigint not null,
  message_id bigint not null,
  emoji text not null default '👍',
  result text,                      -- ответ Telegram (ok / описание ошибки)
  done_at timestamptz,
  created_at timestamptz not null default now()
);
alter table public.bot_actions enable row level security;
grant all on public.bot_actions to service_role;

create function public.notify_bot_action() returns trigger
language plpgsql security definer set search_path = public as $$
declare base text := (select value #>> '{}' from settings where key = 'functions_url');
begin
  if base is not null then
    perform net.http_post(url := base || '/tg-bot?actions=1', headers := '{"Content-Type": "application/json"}'::jsonb,
      body := '{}'::jsonb, timeout_milliseconds := 30000);
  end if;
  return new;
end $$;
create trigger bot_actions_notify after insert on public.bot_actions for each row execute function public.notify_bot_action();
