-- Фото из походов (docs/photos.md). Сами файлы — в бакете ebl-photos в Яндексе: <key>.jpg (до 1600 px) и <key>_s.jpg (превью).
-- Ключ — 32 случайных hex-символа, список бакета закрыт: угадать адрес нельзя, а какие фото у какой бани — знает только база,
-- и видят это только участники лиги (как журнал: на фото люди, дата и компания).
-- Бот кладёт фото сразу, как увидел, а файл перекачивает функция photos (триггер ниже + pg_cron на повторы).
create table public.visit_photos (
  id bigint generated by default as identity primary key,
  visit_id bigint references public.visits(id) on delete cascade,   -- пусто — фото в черновике бота, ещё не отправленном
  draft_msg bigint,                    -- черновик: номер поста, с которого он начался (bot_sessions.state.source)
  added_by uuid not null references public.players(id),
  source text not null check (source in ('bot', 'site')),
  key text not null unique default replace(gen_random_uuid()::text, '-', ''),
  w int, h int,
  ready boolean not null default false,   -- файл уже в бакете
  tries int not null default 0,           -- попытки перекачки из Telegram
  hidden boolean not null default false,  -- скрыла Комиссия
  tg_from bigint,                      -- кто прислал (Telegram): альбом собираем по отправителю
  tg_album text,                       -- media_group_id: фото альбома приходят отдельными сообщениями, подпись — у одного
  tg_file_id text, tg_thumb_id text,   -- откуда забрать: большой размер и превью (Telegram хранит фото в нескольких размерах)
  tg_unique_id text unique,            -- одно и то же фото второй раз не кладём
  created_at timestamptz not null default now()
);
create index on public.visit_photos (visit_id);
create index on public.visit_photos (tg_album) where tg_album is not null;
create index on public.visit_photos (tg_from, draft_msg) where visit_id is null;

alter table public.visit_photos enable row level security;
create policy "фото походов — для участников лиги" on public.visit_photos for select to authenticated
  using (visit_id is not null and ready and (not hidden or public.is_commission()) and public.me() is not null);
grant select on public.visit_photos to authenticated;
grant all on public.visit_photos to service_role;

-- новое фото похода (или черновик отправили) — перекачиваем этот файл сразу, а не ждём расписания
create function public.sync_visit_photo() returns trigger
language plpgsql security definer set search_path = public as $$
declare base text := (select value #>> '{}' from settings where key = 'functions_url');
begin
  if base is not null and new.visit_id is not null and not new.ready and new.source = 'bot' then
    perform net.http_post(url := base || '/photos?sync=' || new.id, headers := '{"Content-Type": "application/json"}'::jsonb,
      body := '{}'::jsonb, timeout_milliseconds := 60000);
  end if;
  return new;
end $$;
create trigger visit_photos_sync after insert or update of visit_id on public.visit_photos
for each row execute function public.sync_visit_photo();

-- повторы: Telegram или Яндекс не ответили — раз в 10 минут, только если есть что докачать;
-- заодно выметаем фото брошенных черновиков (отменили, не отправили за сутки)
select cron.schedule('ebl-photos-sync', '*/10 * * * *', $$
  delete from public.visit_photos where visit_id is null and created_at < now() - interval '1 day';
  select net.http_post(
    url := (select value #>> '{}' from public.settings where key = 'functions_url') || '/photos?sync=all',
    headers := '{"Content-Type": "application/json"}'::jsonb, body := '{}'::jsonb, timeout_milliseconds := 120000)
  where exists (select 1 from public.visit_photos where visit_id is not null and not ready and tries < 5);
$$);
