-- Цена пива в бане — отдельно от цены входа: тот же принцип (любой участник вносит, история не переписывается,
-- дубль по цене и валюте не пишем), но проще — без времени и будни/выходной.
create table public.bath_beer_prices (
  id bigint generated by default as identity primary key,
  bath_id bigint not null references public.baths(id) on delete cascade,
  price numeric not null check (price > 0),
  currency text not null default 'RUB',
  price_date date not null default current_date,
  created_by uuid references public.players(id),
  created_at timestamptz not null default now()
);
create index on public.bath_beer_prices (bath_id, price_date desc);

alter table public.bath_beer_prices enable row level security;
create policy "цены пива видны всем" on public.bath_beer_prices for select using (true);
create policy "Комиссия удаляет неверную цену пива" on public.bath_beer_prices for delete to authenticated using (public.is_commission());

grant select on public.bath_beer_prices to anon, authenticated;
grant delete on public.bath_beer_prices to authenticated;

create function public.submit_beer_price(p_bath_id bigint, p_price numeric, p_currency text) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := public.me();
  v_currency text := upper(coalesce(nullif(btrim(p_currency), ''), 'RUB'));
  v_last numeric;
  v_id bigint;
begin
  if v_me is null then raise exception 'Цены могут вносить участники лиги'; end if;
  if not exists (select 1 from baths where id = p_bath_id and status <> 'rejected') then
    raise exception 'Нет такой бани';
  end if;
  if p_price is null or p_price <= 0 then raise exception 'Цена должна быть больше нуля'; end if;

  select price into v_last from bath_beer_prices
  where bath_id = p_bath_id and currency = v_currency
  order by price_date desc, id desc limit 1;

  if v_last is not null and v_last = p_price then
    return null;   -- цена не изменилась — новую запись не пишем
  end if;

  insert into bath_beer_prices (bath_id, price, currency, created_by)
  values (p_bath_id, p_price, v_currency, v_me)
  returning id into v_id;
  return v_id;
end $$;

revoke all on function public.submit_beer_price(bigint, numeric, text) from public, anon;
grant execute on function public.submit_beer_price(bigint, numeric, text) to authenticated;
