-- Цена бани: складываем то, что участники видят на месте или на сайте бани, чтобы потом строить график по времени.
-- Разряд сейчас не поле здесь — если у бани несколько разрядов, это разные строки в baths (см. docs/data.md);
-- если понадобится цена по разряду внутри одной бани, добавим колонку отдельной миграцией.
-- Цену может внести любой участник; если для тех же валюты и времени цена не изменилась — новую строку не пишем,
-- старые записи не трогаем и не удаляем — это история, а не текущее состояние.
create table public.bath_prices (
  id bigint generated by default as identity primary key,
  bath_id bigint not null references public.baths(id) on delete cascade,
  price numeric not null check (price > 0),
  currency text not null default 'RUB',
  duration_min int check (duration_min > 0),
  price_date date not null default current_date,
  created_by uuid references public.players(id),
  created_at timestamptz not null default now()
);
create index on public.bath_prices (bath_id, price_date desc);

alter table public.bath_prices enable row level security;
create policy "цены видны всем" on public.bath_prices for select using (true);
create policy "Комиссия удаляет неверную цену" on public.bath_prices for delete to authenticated using (public.is_commission());

grant select on public.bath_prices to anon, authenticated;
grant delete on public.bath_prices to authenticated;

create function public.submit_bath_price(p_bath_id bigint, p_price numeric, p_currency text, p_duration_min int) returns bigint
language plpgsql security definer set search_path = public as $$
declare
  v_me uuid := public.me();
  v_currency text := upper(coalesce(nullif(btrim(p_currency), ''), 'RUB'));
  v_last numeric;
  v_id bigint;
begin
  if v_me is null then raise exception 'Цены могут вносить участники лиги'; end if;
  if not exists (select 1 from baths where id = p_bath_id and status <> 'rejected') then
    raise exception 'Нет такой бани';
  end if;
  if p_price is null or p_price <= 0 then raise exception 'Цена должна быть больше нуля'; end if;
  if p_duration_min is not null and p_duration_min <= 0 then raise exception 'Время должно быть больше нуля'; end if;

  select price into v_last from bath_prices
  where bath_id = p_bath_id and currency = v_currency and coalesce(duration_min, -1) = coalesce(p_duration_min, -1)
  order by price_date desc, id desc limit 1;

  if v_last is not null and v_last = p_price then
    return null;   -- цена не изменилась — новую запись не пишем
  end if;

  insert into bath_prices (bath_id, price, currency, duration_min, created_by)
  values (p_bath_id, p_price, v_currency, p_duration_min, v_me)
  returning id into v_id;
  return v_id;
end $$;

revoke all on function public.submit_bath_price(bigint, numeric, text, int) from public, anon;
grant execute on function public.submit_bath_price(bigint, numeric, text, int) to authenticated;
