-- Общие сборы «@eblany»: на какое сообщение бот ответил и какими своими сообщениями — чтобы поправить их правкой
-- (имена в отметках дозаполняются после отправки, без повторных уведомлений) и держать паузу 10 минут между сборами.
create table public.rollcalls (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  chat_username text,              -- публичный чат — ссылка t.me/<username>/<id>, иначе t.me/c/…
  reply_to bigint not null,        -- сообщение, которое позвало всех
  author_tg bigint not null,       -- его автора не отмечаем
  msgs bigint[] not null default '{}',   -- сообщения бота с отметками
  at timestamptz not null default now()
);
create index on public.rollcalls (chat_id, at);
alter table public.rollcalls enable row level security;
grant all on public.rollcalls to service_role;
